feat(nn4k): implement huggingface executor
xionghuaidong/openspg pull request #1
Opened 2023-12-22 07:44 UTC by xionghuaidong

2023-12-22 09:36 UTC, didicout requested changes

2023-12-22 09:36 UTC, didicout commented on python/nn4k/invoker/base.py
> +            o._publish_executors()
有点奇怪。。还是在simple nn hub 构造的时候传进去吧。。

2023-12-22 09:36 UTC, didicout commented on python/nn4k/utils/config_parsing.py
> +def get_field(nn_config: dict, name: str, text: str) -> Any:
加点注释

2023-12-25 07:34 UTC, chenbin11200 commented on python/nn4k/utils/config_parsing.py
> +# Copyright 2023 Ant Group CO., Ltd.
之前好像听到说开源版本这些蚂蚁的copyright不适宜写，这个是否需要再确认下？

2023-12-25 07:42 UTC, chenbin11200 commented on python/nn4k/executor/hugging_face.py
> +    def _load_model(self):
load model是不是做成一个abstract method会更有指向性？这样实现者会清楚不需要在from_config 里去初始化

2023-12-25 07:45 UTC, chenbin11200 commented on python/nn4k/executor/hugging_face.py
> +    def _get_tokenizer(self):
这里有两种方案：
1. 像你这样，不过把get_tokenizer和get_model都做成public method
2. 把tokenizer和model做成property，省略这两个方法。
两种各有利弊，我们可以讨论一下

2023-12-25 07:46 UTC, chenbin11200 commented on python/nn4k/executor/hugging_face.py
> +class HfLLMExecutor(NNExecutor):
这个为什么不是从LLMExecutor继承下来的？

2023-12-25 07:49 UTC, chenbin11200 commented on python/nn4k/invoker/openai_invoker.py
>      def _parse_config(cls, nn_config: dict) -> dict:
对args的处理，我们统一一下？

2023-12-25 07:52 UTC, chenbin11200 requested changes
我先整理一个文档，我们一起讨论一下吧

2023-12-25 07:52 UTC, chenbin11200 commented on python/nn4k/invoker/base.py
>          if nn_config.get("invoker_type", "LLM") == "LLM":
原来我的设计来说，invoker是没有区分类型的必要的。比如这里的openAi invoker，那其实就是就是用了openAi的executor来执行，但是invoker的代码是一样的（只是config不一样）。所以原来的类继承里面，还有一层分类就是opensource和closesource。不过开源版本简化我是可以理解的，不过这个是不是不用复杂化？还是开发中有什么阻碍？

2023-12-25 08:05 UTC, xionghuaidong commented on python/nn4k/utils/config_parsing.py
> +# Copyright 2023 Ant Group CO., Ltd.
这个 copyright 是按鸡饭的开发规范文档里面操作自动生成的。

2023-12-25 08:18 UTC, xionghuaidong commented on python/nn4k/executor/hugging_face.py
> +class HfLLMExecutor(NNExecutor):
done

2023-12-25 08:20 UTC, xionghuaidong commented on python/nn4k/invoker/base.py
>          if nn_config.get("invoker_type", "LLM") == "LLM":
这里主要考虑的是 executor 一般是要提交到一种任务调度器执行，调远程服务和这不太一样。可以再讨论一下确定怎么搞。

2023-12-25 08:31 UTC, xionghuaidong commented on python/nn4k/executor/hugging_face.py
> +    def _load_model(self):
HfLLMExecutor 本身是一个具体的类，不应当把 _load_model 标记成抽象的，标记成抽象的就无法实例化，为了实例化还得加个另外的具体派生类。给基类 LLMExecutor 加一个抽象的 _load_model 方法有一定合理性，不过得和下面评论中的 _get_tokenizer 和 _get_model 综合考虑。

2023-12-25 08:40 UTC, didicout commented on python/nn4k/invoker/base.py
>          if nn_config.get("invoker_type", "LLM") == "LLM":
原先是按 OpenAIExecutor来的，但实现的时候我感觉 openai 它实在算不上一个 Executor。。Executor里也不包含 remote_service 相关的东西。Executor是 并行环境下单个pod内的入口，这个定义跟openai这种对不上。。所以综合来看改成了OpenAIInvoker。。

2023-12-26 05:57 UTC, xionghuaidong commented on python/nn4k/utils/config_parsing.py
> +# Copyright 2023 Ant Group CO., Ltd.
已和鸡饭确认没有问题。

2023-12-26 05:59 UTC, xionghuaidong commented on python/nn4k/executor/hugging_face.py
> +    def _get_tokenizer(self):
后续按讨论结果修改：实现为只读 property，在 _tokenizer 和 _model 为 None 时抛异常，load_model() 方法为两字段赋值。

2023-12-26 06:00 UTC, xionghuaidong commented on python/nn4k/executor/hugging_face.py
> +    def _load_model(self):
后续按讨论结果修改：在 LLMExecutor 添加抽象的 load_model 方法。

2023-12-26 20:09 UTC, xionghuaidong commented on python/nn4k/utils/config_parsing.py
> +def get_field(nn_config: dict, name: str, text: str) -> Any:
done

2023-12-26 20:29 UTC, xionghuaidong commented on python/nn4k/invoker/base.py
> +            o._publish_executors()
done

2024-01-03 02:23 UTC, xionghuaidong commented on python/nn4k/invoker/openai_invoker.py
>      def _parse_config(cls, nn_config: dict) -> dict:
done

2024-01-06 06:37 UTC, xionghuaidong commented
Merged in https://github.com/OpenSPG/openspg/pull/57

2024-01-06 06:37 UTC, closed without merging