refactor(nn4k): update according to review discussion
xionghuaidong/openspg pull request #2
Opened 2023-12-27 03:32 UTC by xionghuaidong

2024-01-03 06:56 UTC, chenbin11200 reviewed
讨论事项

2024-01-03 06:56 UTC, chenbin11200 commented on python/nn4k/nn4k/executor/base.py
> +        for executor_class in reversed(cls._registered_executor_classes):
这个逻辑好像不太对？

2024-01-03 06:56 UTC, chenbin11200 commented on python/nn4k/nn4k/nnhub/__init__.py
下面这些不写在__init__文件里吧？

2024-01-04 09:21 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/__init__.py
> +from .hugging_face import HfLLMExecutor
done

2024-01-04 09:21 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/__init__.py
> +del HfLLMExecutor
fixed

2024-01-04 09:21 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/base.py
> +        self._inference_args = inference_args
fixed

2024-01-04 09:21 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/base.py
> +    def load_model(self, **kwargs):
done

2024-01-04 09:21 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/base.py
> +    def _from_config(cls, nn_config: NNExecutorConfig) -> "NNExecutor":
done

2024-01-04 09:22 UTC, xionghuaidong commented on python/nn4k/nn4k/invoker/base.py
> +class LLMInvokerConfig(NNInvokerConfig):
fixed

2024-01-04 09:22 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/base.py
> +        for executor_class in reversed(cls._registered_executor_classes):
fixed

2024-01-04 09:23 UTC, xionghuaidong commented on python/nn4k/nn4k/nnhub/__init__.py
根据讨论，目前继续写在 ``__init__`` 中。

2024-01-04 09:25 UTC, xionghuaidong commented on python/nn4k/nn4k/executor/base.py
> +    def try_parse_config(
根据讨论，开源 NN4K 只自己解析 nn_name、nn_version 等少数几个字段，灵活的参数解析由派生类自行决定。

2024-01-04 10:54 UTC, didicout requested changes

2024-01-04 10:54 UTC, didicout commented on python/nn4k/nn4k/executor/base.py
> +        from nn4k.invoker import NNInvoker
不要在Executor里import invoker吧。直接import个hub?

2024-01-06 06:38 UTC, xionghuaidong commented
Merged in https://github.com/OpenSPG/openspg/pull/57

2024-01-06 06:38 UTC, closed without merging