feat(nn4k): implement text embeddings
xionghuaidong/openspg pull request #4
Opened 2024-01-18 09:09 UTC by xionghuaidong

2024-01-19 09:36 UTC, didicout requested changes

2024-01-19 09:36 UTC, didicout commented on python/nn4k/nn4k/examples/openai-embeddings/openai_emb.py
> +vecs = invoker.remote_inference(["How old are you?", "What is your age?"])
不对吧，上次对的是 inference里加一个type，type可能是 Embedding、RE、EE等。不是在模型上区分

2024-01-22 10:55 UTC, xionghuaidong commented on python/nn4k/nn4k/examples/openai-embeddings/openai_emb.py
> +vecs = invoker.remote_inference(["How old are you?", "What is your age?"])
fixed

2024-01-26 09:16 UTC, didicout approved these changes

2024-02-02 11:05 UTC, xionghuaidong commented
Merged in https://github.com/OpenSPG/openspg/pull/104

2024-02-02 11:05 UTC, closed without merging